apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - git:
      repoURL: https://github.com/mansong1/guestbook-deploy.git
      revision: main
      files:
      - path: "guestbook/configs/**/config.json"
  template:
    metadata:
      name: 'guestbook-demo-{{cluster_name}}'
    spec:
      project: c8b29069
      source:
        repoURL: https://github.com/wings-software/anshul-test.git
        targetRevision: '{{releaseTag}}'
        path: "vanilla-k8s/apps/app1/{{envName}}"
      destination:
        server: '{{cluster_address}}'
        namespace: gitops-agent
      syncPolicy:
        automated: {}
